on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: pwd

      - name: Print
        run: echo Zaza
      
      - uses: actions/ckeckout@v3
      
      - name: 'Printing folder contents'
        run: ls